-- Lisää INSERT INTO lauseet tähän tiedostoon
INSERT INTO Admin (name, email, hash, super) VALUES ('minad', 'l33t@exam.ple', '$2a$07$pKTBHcqlznn37hRGQOOFzu9.i.CxpUU8n0cVS/aXg8QVY99Z0fEgW', false);
INSERT INTO Admin (name, email, hash, super) VALUES ('ad_min', 'l33test@exam.ple', '$2a$07$nQ4gUb2auEHq0h8AHiLYFueChXdBhJlgswJ46sF.S4UJVg6Ex7o5G', true);
INSERT INTO Board (name, description) VALUES ('v', '!!vidya gaimz!!');
INSERT INTO Board (name, description) VALUES ('pol', 'Such correct');
INSERT INTO AdminBoard (adminId, boardId) VALUES (1, 1);
INSERT INTO Thread (boardId, title) VALUES (1, 'Moba''s');
INSERT INTO Thread (boardId, title) VALUES (1, 'Not diablo');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Thread (boardId, title) VALUES (2, 'Hai');
INSERT INTO Useri (ip) VALUES ('localhost');
INSERT INTO Useri (ip) VALUES ('localhost2');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, 'LoL');
INSERT INTO Post (threadId, userId, content) VALUES (1, 2, '< Dota');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, '< Hots');
INSERT INTO Post (threadId, userId, content) VALUES (1, 2, '< Awesomenauts');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, '< HoN');
INSERT INTO Post (threadId, userId, content) VALUES (1, 2, '< Smite');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, '< Super Monday Night Combat');
INSERT INTO Post (threadId, userId, content) VALUES (1, 2, '< AirMech');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, '< Strife');
INSERT INTO Post (threadId, userId, content) VALUES (1, 2, '< Guardians of Middle-earth');
INSERT INTO Post (threadId, userId, content) VALUES (1, 1, '< LoL');
INSERT INTO Post (threadId, userId, content) VALUES (2, 1, 'Poe''s law');
INSERT INTO Post (threadId, userId, content) VALUES (3, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (4, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (5, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (6, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (7, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (8, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (9, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (10, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (11, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (12, 2, 'Hailstorm');
INSERT INTO Post (threadId, userId, content) VALUES (13, 2, 'Hailstorm');
