-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Admin CASCADE;
DROP TABLE IF EXISTS AdminBoard CASCADE;
DROP TABLE IF EXISTS Board CASCADE;
DROP TABLE IF EXISTS Post CASCADE;
DROP TABLE IF EXISTS Useri CASCADE;
DROP TABLE IF EXISTS Thread CASCADE;
DROP TABLE IF EXISTS Banned CASCADE;
